### ISSUE TITLE
Gulp-Task modular modularisieren (Config-Werte)

### ISSUE THREAD

**Issue by janaHehr** [janaHehr/generator-angular-feature-based#1]
##### To-Do
- ~~Alle Base Task-Files sollten nur einen Task pro Profil "nach außen geben"~~
- ~~Config aufteilen in base und custom~~

**Comment by tklepzig** [comment]
https://github.com/janaHehr/generator-angular-feature-based/commit/b35b22c9bed8aafad829702d837ac9752e93be2f

**Comment by tklepzig** [comment]
https://github.com/janaHehr/generator-angular-feature-based/commit/3ba8f84e12baf6fd07c93aba6b8df179fd03b4e5

**Comment by tklepzig** [comment]
https://github.com/janaHehr/generator-angular-feature-based/commit/80be0dffd7b86fc1bfbd01a316b3683a20b75343

Gulp Tasks bspw. anderer Generatoren können ihre eigene Config mitbringen, die dann im gulpfile.js die bereits vorhandene Config erweitert (s. Kommentare im gulpfile.js).
