### ISSUE TITLE
Sass Files unterhalb von Assets, der mit nach dist kopiert wird

### ISSUE THREAD

**Issue by tklepzig** [janaHehr/generator-angular-feature-based#5]
Was ist da die Intention? Wie soll die Struktur sein?

**Comment by jmeischner** [comment]
Meinst du das am sass files mit im Dist Ordner liegen? Geht's um den Generator oder die gulp file?

**Comment by tklepzig** [comment]
Es geht ums Gulp File. Der zieht einerseits die sass an und baut die css, kopiert die source sass' aber andererseits durch die Regel "Kopiere assets" mit nach dist. Das ist falsch. Ich würde sagen, dass es unterhalb von app einen Ordner "Sass" o.ä. geben sollte, der die sass Files nur für Gulp enthält und der assets Ordner leer erzeugt wird (für Bilder, etc.).

**Comment by jmeischner** [comment]
Schwierige Frage, ich finde eigentlich schon dass die sass files in den Assets Ordner gehören, bzw. finde ich es andersrum blöd, dafür noch mal einen extra Ordner parallel dazu zu machen. Ich finde den copy Assets task könnte man überdenken. Wie genau soll denn die Struktur im Dist Ordner sein? Dort würde ich nämlich versuchen die Hierarchie möglichst flach zu halten und da alles ja über die Index.html eingelinkt wird, d.h. den Bilder Ordner z.b. Direkt in den Main Ordner und so. Was sagt ihr dazu?

Sorry für den vielleicht etwas wirren und super formatierten Text, hab es unterwegs am Handy geschrieben :-D

**Comment by janaHehr** [comment]
2374bb1eb097622f2fe4747d880069e586c2fb26
